sudo: false
language: node_js
node_js: '0.12'
cache:
  directories:
    - node_modules
before_script:
- 'npm install'
script:
- 'npm run node-test'
- 'npm run spec-node'
- 'npm run-script spec'
- 'npm run-script integrate'
after_success:
- 'git config --global user.email "robot@health-samurai.io"'
- 'git config --global user.name "Travis CI Deployer"'
- 'if [ -n "$TRAVIS_TAG" ]; then ./script/bower-release.sh; fi'
